account_id = 211125340848
region = "us-east-1"
email_notification = "sourav.patel@ollion.com"
mw_name = "olli-patch-scan-Amazon-Linux-211125340848-ue1-q"
schedule = "cron(30 12 ? * WED *)"
schedule_timezone = "IST"
allow_unassociated_targets = true
operation = [ "Scan" ]
reboot_option = [ "RebootIfNeeded" ]
operating_system = "AMAZON_LINUX_2023"
approve_after_days = 7
compliance_level = "CRITICAL"
enable_non_security = true
